#language: android
os: linux
#android:
#  components:
#    - build-tools-26.0.2
#   - android-30
#    - extra-google-google_play_services
#    - extra-google-m2repository
#    - extra-android-m2repository
#    - sys-img-x86-android-26
#    - sys-img-armeabi-v7a-android-17
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter pub get
  #- ./flutter/bin/flutter build apk
cache:
  directories:
    - $HOME/.pub-cache
