name: Notely
description: An open-source note-taking app with a focus on simplicity and elegance.
publish_to: "none"
version: "1.0.0+1"
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: "flutter"
  cupertino_icons: "^1.0.0"
  path_provider: ^1.6.27
  flutter_localizations:
    sdk: flutter
  intl: any
dev_dependencies:
  flutter_test:
    sdk: "flutter"
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: "Visby"
      fonts:
        - asset: "assets/fonts/Visby.ttf"
    - family: "Runes"
      fonts:
        - asset: "assets/fonts/Runes.ttf"
  assets:
    - assets/images/logo.png
